Repository rubizza-survival-camp/winter-2018, pull requests merged in 2018-12, with the labels that each got.

#5 Vladislav Pozniak - 0
  Vladislav Pozniak/0/.gitignore
  Vladislav Pozniak/0/Gemfile
  Vladislav Pozniak/0/Gemfile.lock
  Vladislav Pozniak/0/README.md
  Vladislav Pozniak/0/getdata.rb
  Vladislav Pozniak/0/run.rb
Labels: merge ready, taleh.zaliyev

#15 Vladislav Golovkin - 0
  Vladislav Golovkin/0/Gemfile
  Vladislav Golovkin/0/Gemfile.lock
  Vladislav Golovkin/0/README.md
  Vladislav Golovkin/0/main.rb
Labels: merge ready, taleh.zaliyev

#1 Maxim Oberemko - 0
  Maxim Oberemko/0/.gitignore
  Maxim Oberemko/0/Gemfile
  Maxim Oberemko/0/Gemfile.lock
  Maxim Oberemko/0/README.md
  Maxim Oberemko/0/parse.rb
Labels: merge ready

#24 Vasili Makouchyk - 0
  Vasili Makouchyk/0/.gitignore
  Vasili Makouchyk/0/Gemfile
  Vasili Makouchyk/0/Readme.md
  Vasili Makouchyk/0/menu.rb
  Vasili Makouchyk/0/run.rb
Labels: merge ready

#18 Fiodor Borisiuk - 0
  Fiodor Borisiuk/0/Gemfile
  Fiodor Borisiuk/0/Gemfile.lock
  Fiodor Borisiuk/0/Readme.md
  Fiodor Borisiuk/0/downloader.rb
  Fiodor Borisiuk/0/run.rb
Labels: taleh.zaliyev

#40 Pavel Zhachko - 0
  Pavel Zhachko/0/.gitignore
  Pavel Zhachko/0/Gemfile
  Pavel Zhachko/0/Gemfile.lock
  Pavel Zhachko/0/README.md
  Pavel Zhachko/0/parser.rb
  Pavel Zhachko/0/tableconverter.rb
Labels: merge ready
